# Generated by Django 5.0.2 on 2024-03-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Bio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
